---
- hosts: kubernetes-worker-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
    #Copiamos el archivo token en los nodos worker
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token
    #Añadimos los trabajadores al cluster
  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat join_token | tail -2 > out.sh
     sh out.sh
