---
- hosts: kubernetes-master-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
    #Bajamos las imagenes necesarias para kubeadm init
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull
    #Limpiamos cualquier posible rastro de una config anterior
  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output
    #Iniciamos el cluster pasando parametros del archivo env
  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
    register: output
    #Guardamos la salida en el token file necesaria para unir los nodos worker
  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}
    become: False

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
    #Instalamos la red flannel para el cluster
  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    #Instalamos helm para instalar aplicaciones
  - name: Install helm
    shell: |
     curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
     chmod 700 get_helm.sh
     sh get_helm.sh
     rm -f get_helm.sh
