---
- hosts: nfs-server-nodes
  become: yes
  vars_files:
  - env_variables_nfs
  tasks:
  - name: nfs-server
    shell: |
     dnf install nfs-utils -y
  
  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Allow Network Ports in Firewalld for nfs
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
    with_items: "{{ nfs_ports  }}"
